// <auto-generated />
using System;
using JaxPower.Ipqc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaxPower.Ipqc.Api.Data.Migrations
{
    [DbContext(typeof(IpqcDbContext))]
    [Migration("20261003051640_InitialPatrolStandards")]
    partial class InitialPatrolStandards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PatrolStandardName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("StandardNo")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedAtUtc");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("WorkshopCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("FactoryCode");

                    b.HasIndex("LineCode");

                    b.HasIndex("PatrolStandardName");

                    b.ToTable("PatrolStandards");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefectLevel")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("InspectionContent")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("InspectionItem")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("InspectionItemCategory")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("LowerLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("LowerLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<Guid>("PatrolStandardId");

                    b.Property<string>("PhotoRequirement")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("SampleCount")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("SamplingPlan")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("SequenceNo");

                    b.Property<string>("UpperLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("UpperLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolStandardItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany("InspectionItems")
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Navigation("InspectionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
