// <auto-generated />
using System;
using JaxPower.Ipqc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaxPower.Ipqc.Api.Data.Migrations
{
    [DbContext(typeof(IpqcDbContext))]
    [Migration("20261004065509_Phase1ETaskExecutionApproval")]
    partial class Phase1ETaskExecutionApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GenerationNotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId");

                    b.HasIndex("PlanNo")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "EffectiveStartUtc", "EffectiveEndUtc");

                    b.ToTable("PatrolPlans");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlanAssignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatrolPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolPlanId", "AssigneeKey")
                        .IsUnique();

                    b.ToTable("PatrolPlanAssignees");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatrolStandardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactoryCode");

                    b.HasIndex("LineCode");

                    b.HasIndex("PatrolStandardName");

                    b.ToTable("PatrolStandards");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectLevel")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItemCategory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoRequirement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleCount")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplingPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpperLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolStandardItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedInspectorKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentRevisionNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactoryCodeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineCodeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("LineNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialCodeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallInspectionResult")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolPlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNoSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledOccurrenceUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceStandardUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopCodeSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId");

                    b.HasIndex("TaskNo")
                        .IsUnique();

                    b.HasIndex("PatrolPlanId", "ScheduledOccurrenceUtc")
                        .IsUnique();

                    b.HasIndex("Status", "ScheduledOccurrenceUtc");

                    b.ToTable("PatrolTasks");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbnormalCause")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbnormalType")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InspectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectLevel")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItemCategory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsNa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgmentResult")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mold")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoRequirement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleCount")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplingPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourcePatrolStandardItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskItemSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InspectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InspectionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgmentResult")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskItemId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskItemSamples");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskId", "RevisionNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskReviews");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverallInspectionResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskId", "RevisionNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskSubmissions");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbnormalCause")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AbnormalType")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InspectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgmentResult")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineCode")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mold")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskSubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskSubmissionId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskSubmissionItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InspectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InspectionValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("JudgmentResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolTaskSubmissionItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatrolTaskSubmissionItemId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolTaskSubmissionSamples");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany()
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlanAssignee", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolPlan", "PatrolPlan")
                        .WithMany("Assignees")
                        .HasForeignKey("PatrolPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolPlan");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany("InspectionItems")
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTask", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolPlan", "PatrolPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("PatrolPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany()
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatrolPlan");

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskItem", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTask", "PatrolTask")
                        .WithMany("Items")
                        .HasForeignKey("PatrolTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTask");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskItemSample", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTaskItem", "PatrolTaskItem")
                        .WithMany("Samples")
                        .HasForeignKey("PatrolTaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTaskItem");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskReview", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTask", "PatrolTask")
                        .WithMany("Reviews")
                        .HasForeignKey("PatrolTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTask");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmission", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTask", "PatrolTask")
                        .WithMany("Submissions")
                        .HasForeignKey("PatrolTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTask");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionItem", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmission", "PatrolTaskSubmission")
                        .WithMany("Items")
                        .HasForeignKey("PatrolTaskSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTaskSubmission");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionSample", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionItem", "PatrolTaskSubmissionItem")
                        .WithMany("Samples")
                        .HasForeignKey("PatrolTaskSubmissionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolTaskSubmissionItem");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Navigation("InspectionItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTask", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reviews");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskItem", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmission", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTaskSubmissionItem", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
