// <auto-generated />
using System;
using JaxPower.Ipqc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaxPower.Ipqc.Api.Data.Migrations
{
    [DbContext(typeof(IpqcDbContext))]
    [Migration("20261004001954_PatrolPlansAndScheduler")]
    partial class PatrolPlansAndScheduler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GenerationNotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId");

                    b.HasIndex("PlanNo")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "EffectiveStartUtc", "EffectiveEndUtc");

                    b.ToTable("PatrolPlans");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlanAssignee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatrolPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolPlanId", "AssigneeKey")
                        .IsUnique();

                    b.ToTable("PatrolPlanAssignees");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatrolStandardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FactoryCode");

                    b.HasIndex("LineCode");

                    b.HasIndex("PatrolStandardName");

                    b.ToTable("PatrolStandards");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefectLevel")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionItemCategory")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LowerLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoRequirement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleCount")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SamplingPlan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpperLimitOperator")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpperLimitValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId", "SequenceNo")
                        .IsUnique();

                    b.ToTable("PatrolStandardItems");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedInspectorKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolPlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatrolStandardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledOccurrenceUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatrolStandardId");

                    b.HasIndex("TaskNo")
                        .IsUnique();

                    b.HasIndex("PatrolPlanId", "ScheduledOccurrenceUtc")
                        .IsUnique();

                    b.ToTable("PatrolTasks");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany()
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlanAssignee", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolPlan", "PatrolPlan")
                        .WithMany("Assignees")
                        .HasForeignKey("PatrolPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolPlan");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandardItem", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany("InspectionItems")
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolTask", b =>
                {
                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolPlan", "PatrolPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("PatrolPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JaxPower.Ipqc.Api.Domain.PatrolStandard", "PatrolStandard")
                        .WithMany()
                        .HasForeignKey("PatrolStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PatrolPlan");

                    b.Navigation("PatrolStandard");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolPlan", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("JaxPower.Ipqc.Api.Domain.PatrolStandard", b =>
                {
                    b.Navigation("InspectionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
